# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a25b04b94ed8061146bd06285aec1c698631ef26be3bbfb8ae484aaa7f2f7e2584454c5ae74bbde72fe7785a224e3c742da5bcc36144b9fa61d5d1d38db53b68

test:
  secret_key_base: 70e6fe127ca7b38785552a7684eee60f3d76c5db67cc146e48e036150354da0bc049421947174f565d847c7ddab79587df9269fcb6a92da76ff23d1ad86e4112

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
